### ISSUE TITLE
by_common should search all known common names

### ISSUE THREAD

**Issue by cboettig** [cboettig/taxadb#51]
Currently by_common just uses the first available common name which we've grabbed.  When multiple common names are available, this doesn't always give the best choice, so it would be better to check all common names.  (For instance, this makes ITIS use `man` as the vernacular for *Homo sapiens*, and rock cod instead of Atlantic cod for *Gadus morhua*).

**Comment by karinorman** [comment]
@cboettig I'm going to take a look at this. Were you think it would be better for by_common to pull from a separate (but complete) common names table? Or that we should put all the common names in the existing dwc tables?

**Comment by cboettig** [comment]
cool! probably better to put it in a separate common names table
