### ISSUE TITLE
taxadb breaks CI for RNeXML

### ISSUE THREAD

**Issue by hlapp** [cboettig/taxadb#58]
That's because it fails with a 404 to download https://github.com/boettiger-lab/taxadb-cache/releases/download/dwc/dwc.2fcommon_itis.tsv.bz2 here:

https://github.com/cboettig/taxadb/blob/aad9991492e1ec29a5533db1b704fb1a90382134/R/taxa_tbl.R#L37-L39

Supposedly, that's because it fails to follow redirection, because otherwise the download actually works?

**Comment by cboettig** [comment]
Fixed in #57
